### PR TITLE
adding linting and coverage, with minimum code change

### PR DESCRIPTION
**Pull request by alexjavabraz**
- coverage applied
- ci/cd integration
- add auto comment with % of code coverage
- minimum changes on key classes and features
- only little changes in services
- packages below without any changes:
src/datasources/
src/models/
src/repositories/
src/utils/
src/controllers/

### CODE REVIEW

**Review by josedahlquist — CHANGES_REQUESTED** [review]
@ronaldsg20 has a good point about the ignored files.
On the other hand, I don't think rules should be disabled at file level but on a line level.
We should follow the rules and create exceptions when we consider is valid. Having a rule disabled for a whole file allows for future mistakes

**Comment by alexjavabraz** [comment]
> 

The idea here is to work with 3 steps:
1 - Turn on the linting rules in the project with minimum changes, reaching only the essential files. Once the linting is running well we can advance.
2 - Turn on the linting rules on services and complex files
3 - Turn on the linting rules on the more complex files

The first version of the PR contained almost 200 modifications, for this reason we're working with 3 steps implementation.

**Review by hard75 — APPROVED** [review]
coverage checked

**Review by josedahlquist — APPROVED** [review]

**Review by leoiovlabs — APPROVED** [review]
LGTM

**Pull request merged**
