### PR TITLE
Resolve dependabot alerts

### PR DESCRIPTION
**Pull request by lserra-iov**
- Bump undici from 5.25.2 to 5.26.3
- Bump @babel/traverse from 7.15.4 to 7.23.2

### CODE REVIEW

**Review by alexjavabraz — COMMENTED** [review]
there are no changes in package.json ?

**Comment by lserra-iov** [comment]
> there are no changes in package.json ?

No, just indirect dependencies updates

**Review by alexjavabraz — APPROVED** [review]
LGTM

**Review by alexjavabraz — APPROVED** [review]
LGTM

**Review by ronaldsg20 — APPROVED** [review]

**Review by leoiovlabs — APPROVED** [review]
LGTM

**Pull request merged**
